// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runner_registration_v1.proto

package runnerregistrationv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RunnerRegistrationServiceName is the fully-qualified name of the RunnerRegistrationService
	// service.
	RunnerRegistrationServiceName = "bountyhub.runner.registration.v1.RunnerRegistrationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RunnerRegistrationServiceRegisterRunnerProcedure is the fully-qualified name of the
	// RunnerRegistrationService's RegisterRunner RPC.
	RunnerRegistrationServiceRegisterRunnerProcedure = "/bountyhub.runner.registration.v1.RunnerRegistrationService/RegisterRunner"
)

// RunnerRegistrationServiceClient is a client for the
// bountyhub.runner.registration.v1.RunnerRegistrationService service.
type RunnerRegistrationServiceClient interface {
	RegisterRunner(context.Context, *connect.Request[RegisterRunnerRequest]) (*connect.Response[RegisterRunnerResponse], error)
}

// NewRunnerRegistrationServiceClient constructs a client for the
// bountyhub.runner.registration.v1.RunnerRegistrationService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRunnerRegistrationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RunnerRegistrationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	runnerRegistrationServiceMethods := File_runner_registration_v1_proto.Services().ByName("RunnerRegistrationService").Methods()
	return &runnerRegistrationServiceClient{
		registerRunner: connect.NewClient[RegisterRunnerRequest, RegisterRunnerResponse](
			httpClient,
			baseURL+RunnerRegistrationServiceRegisterRunnerProcedure,
			connect.WithSchema(runnerRegistrationServiceMethods.ByName("RegisterRunner")),
			connect.WithClientOptions(opts...),
		),
	}
}

// runnerRegistrationServiceClient implements RunnerRegistrationServiceClient.
type runnerRegistrationServiceClient struct {
	registerRunner *connect.Client[RegisterRunnerRequest, RegisterRunnerResponse]
}

// RegisterRunner calls bountyhub.runner.registration.v1.RunnerRegistrationService.RegisterRunner.
func (c *runnerRegistrationServiceClient) RegisterRunner(ctx context.Context, req *connect.Request[RegisterRunnerRequest]) (*connect.Response[RegisterRunnerResponse], error) {
	return c.registerRunner.CallUnary(ctx, req)
}

// RunnerRegistrationServiceHandler is an implementation of the
// bountyhub.runner.registration.v1.RunnerRegistrationService service.
type RunnerRegistrationServiceHandler interface {
	RegisterRunner(context.Context, *connect.Request[RegisterRunnerRequest]) (*connect.Response[RegisterRunnerResponse], error)
}

// NewRunnerRegistrationServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRunnerRegistrationServiceHandler(svc RunnerRegistrationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	runnerRegistrationServiceMethods := File_runner_registration_v1_proto.Services().ByName("RunnerRegistrationService").Methods()
	runnerRegistrationServiceRegisterRunnerHandler := connect.NewUnaryHandler(
		RunnerRegistrationServiceRegisterRunnerProcedure,
		svc.RegisterRunner,
		connect.WithSchema(runnerRegistrationServiceMethods.ByName("RegisterRunner")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bountyhub.runner.registration.v1.RunnerRegistrationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RunnerRegistrationServiceRegisterRunnerProcedure:
			runnerRegistrationServiceRegisterRunnerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRunnerRegistrationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRunnerRegistrationServiceHandler struct{}

func (UnimplementedRunnerRegistrationServiceHandler) RegisterRunner(context.Context, *connect.Request[RegisterRunnerRequest]) (*connect.Response[RegisterRunnerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bountyhub.runner.registration.v1.RunnerRegistrationService.RegisterRunner is not implemented"))
}
