// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runner_registration_v1.proto

package runnerregistrationv1connect

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRunnerRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRunnerRegistrationRequest) Reset() {
	*x = CreateRunnerRegistrationRequest{}
	mi := &file_runner_registration_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunnerRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunnerRegistrationRequest) ProtoMessage() {}

func (x *CreateRunnerRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_registration_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunnerRegistrationRequest.ProtoReflect.Descriptor instead.
func (*CreateRunnerRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_runner_registration_v1_proto_rawDescGZIP(), []int{0}
}

type CreateRunnerRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRunnerRegistrationResponse) Reset() {
	*x = CreateRunnerRegistrationResponse{}
	mi := &file_runner_registration_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunnerRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunnerRegistrationResponse) ProtoMessage() {}

func (x *CreateRunnerRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_registration_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunnerRegistrationResponse.ProtoReflect.Descriptor instead.
func (*CreateRunnerRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_runner_registration_v1_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRunnerRegistrationResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateRunnerRegistrationResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WorkDir       string                 `protobuf:"bytes,3,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Replace       bool                   `protobuf:"varint,4,opt,name=replace,proto3" json:"replace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRunnerRequest) Reset() {
	*x = RegisterRunnerRequest{}
	mi := &file_runner_registration_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRunnerRequest) ProtoMessage() {}

func (x *RegisterRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_registration_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRunnerRequest.ProtoReflect.Descriptor instead.
func (*RegisterRunnerRequest) Descriptor() ([]byte, []int) {
	return file_runner_registration_v1_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRunnerRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRunnerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRunnerRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *RegisterRunnerRequest) GetReplace() bool {
	if x != nil {
		return x.Replace
	}
	return false
}

type RegisterRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRunnerResponse) Reset() {
	*x = RegisterRunnerResponse{}
	mi := &file_runner_registration_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRunnerResponse) ProtoMessage() {}

func (x *RegisterRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_registration_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRunnerResponse.ProtoReflect.Descriptor instead.
func (*RegisterRunnerResponse) Descriptor() ([]byte, []int) {
	return file_runner_registration_v1_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRunnerResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_runner_registration_v1_proto protoreflect.FileDescriptor

const file_runner_registration_v1_proto_rawDesc = "" +
	"\n" +
	"\x1crunner_registration_v1.proto\x12 bountyhub.runner.registration.v1\x1a\x1cgoogle/api/annotations.proto\"!\n" +
	"\x1fCreateRunnerRegistrationRequest\"J\n" +
	" CreateRunnerRegistrationResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"v\n" +
	"\x15RegisterRunnerRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bwork_dir\x18\x03 \x01(\tR\aworkDir\x12\x18\n" +
	"\areplace\x18\x04 \x01(\bR\areplace\".\n" +
	"\x16RegisterRunnerResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xcf\x01\n" +
	"\x19RunnerRegistrationService\x12\xb1\x01\n" +
	"\x0eRegisterRunner\x127.bountyhub.runner.registration.v1.RegisterRunnerRequest\x1a8.bountyhub.runner.registration.v1.RegisterRunnerResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/runner-registrations/registerB\xa5\x02\n" +
	"$com.bountyhub.runner.registration.v1B\x19RunnerRegistrationV1ProtoP\x01Z?github.com/bountyhub-org/runner/api/runnerregistrationv1connect\xa2\x02\x03BRR\xaa\x02 Bountyhub.Runner.Registration.V1\xca\x02 Bountyhub\\Runner\\Registration\\V1\xe2\x02,Bountyhub\\Runner\\Registration\\V1\\GPBMetadata\xea\x02#Bountyhub::Runner::Registration::V1b\x06proto3"

var (
	file_runner_registration_v1_proto_rawDescOnce sync.Once
	file_runner_registration_v1_proto_rawDescData []byte
)

func file_runner_registration_v1_proto_rawDescGZIP() []byte {
	file_runner_registration_v1_proto_rawDescOnce.Do(func() {
		file_runner_registration_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_registration_v1_proto_rawDesc), len(file_runner_registration_v1_proto_rawDesc)))
	})
	return file_runner_registration_v1_proto_rawDescData
}

var file_runner_registration_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_runner_registration_v1_proto_goTypes = []any{
	(*CreateRunnerRegistrationRequest)(nil),  // 0: bountyhub.runner.registration.v1.CreateRunnerRegistrationRequest
	(*CreateRunnerRegistrationResponse)(nil), // 1: bountyhub.runner.registration.v1.CreateRunnerRegistrationResponse
	(*RegisterRunnerRequest)(nil),            // 2: bountyhub.runner.registration.v1.RegisterRunnerRequest
	(*RegisterRunnerResponse)(nil),           // 3: bountyhub.runner.registration.v1.RegisterRunnerResponse
}
var file_runner_registration_v1_proto_depIdxs = []int32{
	2, // 0: bountyhub.runner.registration.v1.RunnerRegistrationService.RegisterRunner:input_type -> bountyhub.runner.registration.v1.RegisterRunnerRequest
	3, // 1: bountyhub.runner.registration.v1.RunnerRegistrationService.RegisterRunner:output_type -> bountyhub.runner.registration.v1.RegisterRunnerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runner_registration_v1_proto_init() }
func file_runner_registration_v1_proto_init() {
	if File_runner_registration_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_registration_v1_proto_rawDesc), len(file_runner_registration_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runner_registration_v1_proto_goTypes,
		DependencyIndexes: file_runner_registration_v1_proto_depIdxs,
		MessageInfos:      file_runner_registration_v1_proto_msgTypes,
	}.Build()
	File_runner_registration_v1_proto = out.File
	file_runner_registration_v1_proto_goTypes = nil
	file_runner_registration_v1_proto_depIdxs = nil
}
