name: "Runner Feature Request"
description: "Create a feature request"
labels: ["enhancement", "needs triage", "platform"]
assignees: ["nikola-jokic"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Check the following before submitting a feature request
      options:
        - label: I have searched the issues of this repository and believe that this is not a duplicate
          required: true
        - label: I have read the docs and I'm sure this is a feature request
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
      placeholder: A clear and concise description of what the feature is.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: A clear and concise description of why you need this feature.
      placeholder: A clear and concise description of why you need this feature.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
      render: markdown
