// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: job_assignment_v1.proto

package jobassignmentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// JobAssignmentServiceName is the fully-qualified name of the JobAssignmentService service.
	JobAssignmentServiceName = "bountyhub.job.assignment.v1.JobAssignmentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// JobAssignmentServiceAcquireJobsProcedure is the fully-qualified name of the
	// JobAssignmentService's AcquireJobs RPC.
	JobAssignmentServiceAcquireJobsProcedure = "/bountyhub.job.assignment.v1.JobAssignmentService/AcquireJobs"
	// JobAssignmentServiceAcquireJobSessionsProcedure is the fully-qualified name of the
	// JobAssignmentService's AcquireJobSessions RPC.
	JobAssignmentServiceAcquireJobSessionsProcedure = "/bountyhub.job.assignment.v1.JobAssignmentService/AcquireJobSessions"
)

// JobAssignmentServiceClient is a client for the bountyhub.job.assignment.v1.JobAssignmentService
// service.
type JobAssignmentServiceClient interface {
	AcquireJobs(context.Context, *connect.Request[AcquireJobsRequest]) (*connect.Response[AcquireJobsResponse], error)
	AcquireJobSessions(context.Context, *connect.Request[AcquireJobSessionsRequest]) (*connect.Response[AcquireJobSessionsResponse], error)
}

// NewJobAssignmentServiceClient constructs a client for the
// bountyhub.job.assignment.v1.JobAssignmentService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewJobAssignmentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) JobAssignmentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	jobAssignmentServiceMethods := File_job_assignment_v1_proto.Services().ByName("JobAssignmentService").Methods()
	return &jobAssignmentServiceClient{
		acquireJobs: connect.NewClient[AcquireJobsRequest, AcquireJobsResponse](
			httpClient,
			baseURL+JobAssignmentServiceAcquireJobsProcedure,
			connect.WithSchema(jobAssignmentServiceMethods.ByName("AcquireJobs")),
			connect.WithClientOptions(opts...),
		),
		acquireJobSessions: connect.NewClient[AcquireJobSessionsRequest, AcquireJobSessionsResponse](
			httpClient,
			baseURL+JobAssignmentServiceAcquireJobSessionsProcedure,
			connect.WithSchema(jobAssignmentServiceMethods.ByName("AcquireJobSessions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// jobAssignmentServiceClient implements JobAssignmentServiceClient.
type jobAssignmentServiceClient struct {
	acquireJobs        *connect.Client[AcquireJobsRequest, AcquireJobsResponse]
	acquireJobSessions *connect.Client[AcquireJobSessionsRequest, AcquireJobSessionsResponse]
}

// AcquireJobs calls bountyhub.job.assignment.v1.JobAssignmentService.AcquireJobs.
func (c *jobAssignmentServiceClient) AcquireJobs(ctx context.Context, req *connect.Request[AcquireJobsRequest]) (*connect.Response[AcquireJobsResponse], error) {
	return c.acquireJobs.CallUnary(ctx, req)
}

// AcquireJobSessions calls bountyhub.job.assignment.v1.JobAssignmentService.AcquireJobSessions.
func (c *jobAssignmentServiceClient) AcquireJobSessions(ctx context.Context, req *connect.Request[AcquireJobSessionsRequest]) (*connect.Response[AcquireJobSessionsResponse], error) {
	return c.acquireJobSessions.CallUnary(ctx, req)
}

// JobAssignmentServiceHandler is an implementation of the
// bountyhub.job.assignment.v1.JobAssignmentService service.
type JobAssignmentServiceHandler interface {
	AcquireJobs(context.Context, *connect.Request[AcquireJobsRequest]) (*connect.Response[AcquireJobsResponse], error)
	AcquireJobSessions(context.Context, *connect.Request[AcquireJobSessionsRequest]) (*connect.Response[AcquireJobSessionsResponse], error)
}

// NewJobAssignmentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewJobAssignmentServiceHandler(svc JobAssignmentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	jobAssignmentServiceMethods := File_job_assignment_v1_proto.Services().ByName("JobAssignmentService").Methods()
	jobAssignmentServiceAcquireJobsHandler := connect.NewUnaryHandler(
		JobAssignmentServiceAcquireJobsProcedure,
		svc.AcquireJobs,
		connect.WithSchema(jobAssignmentServiceMethods.ByName("AcquireJobs")),
		connect.WithHandlerOptions(opts...),
	)
	jobAssignmentServiceAcquireJobSessionsHandler := connect.NewUnaryHandler(
		JobAssignmentServiceAcquireJobSessionsProcedure,
		svc.AcquireJobSessions,
		connect.WithSchema(jobAssignmentServiceMethods.ByName("AcquireJobSessions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bountyhub.job.assignment.v1.JobAssignmentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case JobAssignmentServiceAcquireJobsProcedure:
			jobAssignmentServiceAcquireJobsHandler.ServeHTTP(w, r)
		case JobAssignmentServiceAcquireJobSessionsProcedure:
			jobAssignmentServiceAcquireJobSessionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedJobAssignmentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedJobAssignmentServiceHandler struct{}

func (UnimplementedJobAssignmentServiceHandler) AcquireJobs(context.Context, *connect.Request[AcquireJobsRequest]) (*connect.Response[AcquireJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bountyhub.job.assignment.v1.JobAssignmentService.AcquireJobs is not implemented"))
}

func (UnimplementedJobAssignmentServiceHandler) AcquireJobSessions(context.Context, *connect.Request[AcquireJobSessionsRequest]) (*connect.Response[AcquireJobSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bountyhub.job.assignment.v1.JobAssignmentService.AcquireJobSessions is not implemented"))
}
