// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: job_assignment_v1.proto

package jobassignmentv1connect

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcquireJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      uint32                 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireJobsRequest) Reset() {
	*x = AcquireJobsRequest{}
	mi := &file_job_assignment_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireJobsRequest) ProtoMessage() {}

func (x *AcquireJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_assignment_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireJobsRequest.ProtoReflect.Descriptor instead.
func (*AcquireJobsRequest) Descriptor() ([]byte, []int) {
	return file_job_assignment_v1_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireJobsRequest) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type AcquireJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*JobAssignment       `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireJobsResponse) Reset() {
	*x = AcquireJobsResponse{}
	mi := &file_job_assignment_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireJobsResponse) ProtoMessage() {}

func (x *AcquireJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_assignment_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireJobsResponse.ProtoReflect.Descriptor instead.
func (*AcquireJobsResponse) Descriptor() ([]byte, []int) {
	return file_job_assignment_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireJobsResponse) GetAssignments() []*JobAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type JobAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Session       string                 `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAssignment) Reset() {
	*x = JobAssignment{}
	mi := &file_job_assignment_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignment) ProtoMessage() {}

func (x *JobAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_job_assignment_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignment.ProtoReflect.Descriptor instead.
func (*JobAssignment) Descriptor() ([]byte, []int) {
	return file_job_assignment_v1_proto_rawDescGZIP(), []int{2}
}

func (x *JobAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssignment) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

var File_job_assignment_v1_proto protoreflect.FileDescriptor

const file_job_assignment_v1_proto_rawDesc = "" +
	"\n" +
	"\x17job_assignment_v1.proto\x12\x1bbountyhub.job.assignment.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\x12AcquireJobsRequest\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\rR\bcapacity\"c\n" +
	"\x13AcquireJobsResponse\x12L\n" +
	"\vassignments\x18\x01 \x03(\v2*.bountyhub.job.assignment.v1.JobAssignmentR\vassignments\"@\n" +
	"\rJobAssignment\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x18\n" +
	"\asession\x18\x03 \x01(\tR\asession2\xb2\x01\n" +
	"\x14JobAssignmentService\x12\x99\x01\n" +
	"\vAcquireJobs\x12/.bountyhub.job.assignment.v1.AcquireJobsRequest\x1a0.bountyhub.job.assignment.v1.AcquireJobsResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/jobs/assignments/acquireB<Z:github.com/bountyhub-org/runner/api/jobassignmentv1connectb\x06proto3"

var (
	file_job_assignment_v1_proto_rawDescOnce sync.Once
	file_job_assignment_v1_proto_rawDescData []byte
)

func file_job_assignment_v1_proto_rawDescGZIP() []byte {
	file_job_assignment_v1_proto_rawDescOnce.Do(func() {
		file_job_assignment_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_assignment_v1_proto_rawDesc), len(file_job_assignment_v1_proto_rawDesc)))
	})
	return file_job_assignment_v1_proto_rawDescData
}

var file_job_assignment_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_job_assignment_v1_proto_goTypes = []any{
	(*AcquireJobsRequest)(nil),  // 0: bountyhub.job.assignment.v1.AcquireJobsRequest
	(*AcquireJobsResponse)(nil), // 1: bountyhub.job.assignment.v1.AcquireJobsResponse
	(*JobAssignment)(nil),       // 2: bountyhub.job.assignment.v1.JobAssignment
}
var file_job_assignment_v1_proto_depIdxs = []int32{
	2, // 0: bountyhub.job.assignment.v1.AcquireJobsResponse.assignments:type_name -> bountyhub.job.assignment.v1.JobAssignment
	0, // 1: bountyhub.job.assignment.v1.JobAssignmentService.AcquireJobs:input_type -> bountyhub.job.assignment.v1.AcquireJobsRequest
	1, // 2: bountyhub.job.assignment.v1.JobAssignmentService.AcquireJobs:output_type -> bountyhub.job.assignment.v1.AcquireJobsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_job_assignment_v1_proto_init() }
func file_job_assignment_v1_proto_init() {
	if File_job_assignment_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_assignment_v1_proto_rawDesc), len(file_job_assignment_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_assignment_v1_proto_goTypes,
		DependencyIndexes: file_job_assignment_v1_proto_depIdxs,
		MessageInfos:      file_job_assignment_v1_proto_msgTypes,
	}.Build()
	File_job_assignment_v1_proto = out.File
	file_job_assignment_v1_proto_goTypes = nil
	file_job_assignment_v1_proto_depIdxs = nil
}
