// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: job_assignment_v1.proto

package jobassignmentv1connect

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcquireJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      uint32                 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireJobsRequest) Reset() {
	*x = AcquireJobsRequest{}
	mi := &file_job_assignment_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireJobsRequest) ProtoMessage() {}

func (x *AcquireJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_assignment_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireJobsRequest.ProtoReflect.Descriptor instead.
func (*AcquireJobsRequest) Descriptor() ([]byte, []int) {
	return file_job_assignment_v1_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireJobsRequest) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type AcquireJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*JobAssignment       `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireJobsResponse) Reset() {
	*x = AcquireJobsResponse{}
	mi := &file_job_assignment_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireJobsResponse) ProtoMessage() {}

func (x *AcquireJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_assignment_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireJobsResponse.ProtoReflect.Descriptor instead.
func (*AcquireJobsResponse) Descriptor() ([]byte, []int) {
	return file_job_assignment_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireJobsResponse) GetAssignments() []*JobAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type JobAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAssignment) Reset() {
	*x = JobAssignment{}
	mi := &file_job_assignment_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignment) ProtoMessage() {}

func (x *JobAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_job_assignment_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignment.ProtoReflect.Descriptor instead.
func (*JobAssignment) Descriptor() ([]byte, []int) {
	return file_job_assignment_v1_proto_rawDescGZIP(), []int{2}
}

func (x *JobAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type AcquireJobSessionsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AcquireSessions []*AcquireJobSession   `protobuf:"bytes,1,rep,name=acquire_sessions,json=acquireSessions,proto3" json:"acquire_sessions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcquireJobSessionsRequest) Reset() {
	*x = AcquireJobSessionsRequest{}
	mi := &file_job_assignment_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireJobSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireJobSessionsRequest) ProtoMessage() {}

func (x *AcquireJobSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_assignment_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireJobSessionsRequest.ProtoReflect.Descriptor instead.
func (*AcquireJobSessionsRequest) Descriptor() ([]byte, []int) {
	return file_job_assignment_v1_proto_rawDescGZIP(), []int{3}
}

func (x *AcquireJobSessionsRequest) GetAcquireSessions() []*AcquireJobSession {
	if x != nil {
		return x.AcquireSessions
	}
	return nil
}

type AcquireJobSession struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	SessionDuration *durationpb.Duration   `protobuf:"bytes,2,opt,name=session_duration,json=sessionDuration,proto3" json:"session_duration,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcquireJobSession) Reset() {
	*x = AcquireJobSession{}
	mi := &file_job_assignment_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireJobSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireJobSession) ProtoMessage() {}

func (x *AcquireJobSession) ProtoReflect() protoreflect.Message {
	mi := &file_job_assignment_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireJobSession.ProtoReflect.Descriptor instead.
func (*AcquireJobSession) Descriptor() ([]byte, []int) {
	return file_job_assignment_v1_proto_rawDescGZIP(), []int{4}
}

func (x *AcquireJobSession) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AcquireJobSession) GetSessionDuration() *durationpb.Duration {
	if x != nil {
		return x.SessionDuration
	}
	return nil
}

type AcquireJobSessionsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Assignments   []*JobSessionAssignment `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireJobSessionsResponse) Reset() {
	*x = AcquireJobSessionsResponse{}
	mi := &file_job_assignment_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireJobSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireJobSessionsResponse) ProtoMessage() {}

func (x *AcquireJobSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_assignment_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireJobSessionsResponse.ProtoReflect.Descriptor instead.
func (*AcquireJobSessionsResponse) Descriptor() ([]byte, []int) {
	return file_job_assignment_v1_proto_rawDescGZIP(), []int{5}
}

func (x *AcquireJobSessionsResponse) GetAssignments() []*JobSessionAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type JobSessionAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSessionAssignment) Reset() {
	*x = JobSessionAssignment{}
	mi := &file_job_assignment_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSessionAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSessionAssignment) ProtoMessage() {}

func (x *JobSessionAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_job_assignment_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSessionAssignment.ProtoReflect.Descriptor instead.
func (*JobSessionAssignment) Descriptor() ([]byte, []int) {
	return file_job_assignment_v1_proto_rawDescGZIP(), []int{6}
}

func (x *JobSessionAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobSessionAssignment) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_job_assignment_v1_proto protoreflect.FileDescriptor

const file_job_assignment_v1_proto_rawDesc = "" +
	"\n" +
	"\x17job_assignment_v1.proto\x12\x1bbountyhub.job.assignment.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/duration.proto\"0\n" +
	"\x12AcquireJobsRequest\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\rR\bcapacity\"c\n" +
	"\x13AcquireJobsResponse\x12L\n" +
	"\vassignments\x18\x01 \x03(\v2*.bountyhub.job.assignment.v1.JobAssignmentR\vassignments\"&\n" +
	"\rJobAssignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"v\n" +
	"\x19AcquireJobSessionsRequest\x12Y\n" +
	"\x10acquire_sessions\x18\x01 \x03(\v2..bountyhub.job.assignment.v1.AcquireJobSessionR\x0facquireSessions\"p\n" +
	"\x11AcquireJobSession\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12D\n" +
	"\x10session_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0fsessionDuration\"q\n" +
	"\x1aAcquireJobSessionsResponse\x12S\n" +
	"\vassignments\x18\x01 \x03(\v21.bountyhub.job.assignment.v1.JobSessionAssignmentR\vassignments\"L\n" +
	"\x14JobSessionAssignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId2\xec\x02\n" +
	"\x14JobAssignmentService\x12\x99\x01\n" +
	"\vAcquireJobs\x12/.bountyhub.job.assignment.v1.AcquireJobsRequest\x1a0.bountyhub.job.assignment.v1.AcquireJobsResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/jobs/assignments/acquire\x12\xb7\x01\n" +
	"\x12AcquireJobSessions\x126.bountyhub.job.assignment.v1.AcquireJobSessionsRequest\x1a7.bountyhub.job.assignment.v1.AcquireJobSessionsResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/jobs/assignments/sessions/acquireB\x82\x02\n" +
	"\x1fcom.bountyhub.job.assignment.v1B\x14JobAssignmentV1ProtoP\x01Z:github.com/bountyhub-org/runner/api/jobassignmentv1connect\xa2\x02\x03BJA\xaa\x02\x1bBountyhub.Job.Assignment.V1\xca\x02\x1bBountyhub\\Job\\Assignment\\V1\xe2\x02'Bountyhub\\Job\\Assignment\\V1\\GPBMetadata\xea\x02\x1eBountyhub::Job::Assignment::V1b\x06proto3"

var (
	file_job_assignment_v1_proto_rawDescOnce sync.Once
	file_job_assignment_v1_proto_rawDescData []byte
)

func file_job_assignment_v1_proto_rawDescGZIP() []byte {
	file_job_assignment_v1_proto_rawDescOnce.Do(func() {
		file_job_assignment_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_assignment_v1_proto_rawDesc), len(file_job_assignment_v1_proto_rawDesc)))
	})
	return file_job_assignment_v1_proto_rawDescData
}

var file_job_assignment_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_job_assignment_v1_proto_goTypes = []any{
	(*AcquireJobsRequest)(nil),         // 0: bountyhub.job.assignment.v1.AcquireJobsRequest
	(*AcquireJobsResponse)(nil),        // 1: bountyhub.job.assignment.v1.AcquireJobsResponse
	(*JobAssignment)(nil),              // 2: bountyhub.job.assignment.v1.JobAssignment
	(*AcquireJobSessionsRequest)(nil),  // 3: bountyhub.job.assignment.v1.AcquireJobSessionsRequest
	(*AcquireJobSession)(nil),          // 4: bountyhub.job.assignment.v1.AcquireJobSession
	(*AcquireJobSessionsResponse)(nil), // 5: bountyhub.job.assignment.v1.AcquireJobSessionsResponse
	(*JobSessionAssignment)(nil),       // 6: bountyhub.job.assignment.v1.JobSessionAssignment
	(*durationpb.Duration)(nil),        // 7: google.protobuf.Duration
}
var file_job_assignment_v1_proto_depIdxs = []int32{
	2, // 0: bountyhub.job.assignment.v1.AcquireJobsResponse.assignments:type_name -> bountyhub.job.assignment.v1.JobAssignment
	4, // 1: bountyhub.job.assignment.v1.AcquireJobSessionsRequest.acquire_sessions:type_name -> bountyhub.job.assignment.v1.AcquireJobSession
	7, // 2: bountyhub.job.assignment.v1.AcquireJobSession.session_duration:type_name -> google.protobuf.Duration
	6, // 3: bountyhub.job.assignment.v1.AcquireJobSessionsResponse.assignments:type_name -> bountyhub.job.assignment.v1.JobSessionAssignment
	0, // 4: bountyhub.job.assignment.v1.JobAssignmentService.AcquireJobs:input_type -> bountyhub.job.assignment.v1.AcquireJobsRequest
	3, // 5: bountyhub.job.assignment.v1.JobAssignmentService.AcquireJobSessions:input_type -> bountyhub.job.assignment.v1.AcquireJobSessionsRequest
	1, // 6: bountyhub.job.assignment.v1.JobAssignmentService.AcquireJobs:output_type -> bountyhub.job.assignment.v1.AcquireJobsResponse
	5, // 7: bountyhub.job.assignment.v1.JobAssignmentService.AcquireJobSessions:output_type -> bountyhub.job.assignment.v1.AcquireJobSessionsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_job_assignment_v1_proto_init() }
func file_job_assignment_v1_proto_init() {
	if File_job_assignment_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_assignment_v1_proto_rawDesc), len(file_job_assignment_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_assignment_v1_proto_goTypes,
		DependencyIndexes: file_job_assignment_v1_proto_depIdxs,
		MessageInfos:      file_job_assignment_v1_proto_msgTypes,
	}.Build()
	File_job_assignment_v1_proto = out.File
	file_job_assignment_v1_proto_goTypes = nil
	file_job_assignment_v1_proto_depIdxs = nil
}
