syntax = "proto3";

package bountyhub.job.assignment.v1;

import "google/api/annotations.proto";
import "google/protobuf/duration.proto";

service JobAssignmentService {
  rpc AcquireJobs(AcquireJobsRequest) returns (AcquireJobsResponse) {
    option (google.api.http) = {
      post: "/v1/jobs/assignments/acquire"
      body: "*"
    };
  }
  rpc AcquireJobSessions(AcquireJobSessionsRequest) returns (AcquireJobSessionsResponse) {
    option (google.api.http) = {
      post: "/v1/jobs/assignments/sessions/acquire"
      body: "*"
    };
  }
}

message AcquireJobsRequest {
  uint32 capacity = 1;
}

message AcquireJobsResponse {
  repeated JobAssignment assignments = 1;
}

message JobAssignment {
  string job_id = 1;
}

message AcquireJobSessionsRequest {
  repeated AcquireJobSession acquire_sessions = 1;
}

message AcquireJobSession {
  string job_id = 1;
  google.protobuf.Duration session_duration = 2;
}

message AcquireJobSessionsResponse {
  repeated JobSessionAssignment assignments = 1;
}

message JobSessionAssignment {
  string job_id = 1;
  string session_id = 2;
}
