// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/job_execution_v1.proto

package jobexecutionv1connect

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Copy of bountyhub.job.v1.JobOutcome for use in JobExecutionService
// without importing the entire job.proto
type JobOutcome int32

const (
	JobOutcome_JOB_OUTCOME_UNSPECIFIED JobOutcome = 0
	JobOutcome_JOB_OUTCOME_SUCCESS     JobOutcome = 1
	JobOutcome_JOB_OUTCOME_FAILURE     JobOutcome = 2
	JobOutcome_JOB_OUTCOME_CANCELLED   JobOutcome = 3
)

// Enum value maps for JobOutcome.
var (
	JobOutcome_name = map[int32]string{
		0: "JOB_OUTCOME_UNSPECIFIED",
		1: "JOB_OUTCOME_SUCCESS",
		2: "JOB_OUTCOME_FAILURE",
		3: "JOB_OUTCOME_CANCELLED",
	}
	JobOutcome_value = map[string]int32{
		"JOB_OUTCOME_UNSPECIFIED": 0,
		"JOB_OUTCOME_SUCCESS":     1,
		"JOB_OUTCOME_FAILURE":     2,
		"JOB_OUTCOME_CANCELLED":   3,
	}
)

func (x JobOutcome) Enum() *JobOutcome {
	p := new(JobOutcome)
	*p = x
	return p
}

func (x JobOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_services_job_execution_v1_proto_enumTypes[0].Descriptor()
}

func (JobOutcome) Type() protoreflect.EnumType {
	return &file_services_job_execution_v1_proto_enumTypes[0]
}

func (x JobOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobOutcome.Descriptor instead.
func (JobOutcome) EnumDescriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{0}
}

type RequestJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      uint64                 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestJobsRequest) Reset() {
	*x = RequestJobsRequest{}
	mi := &file_services_job_execution_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJobsRequest) ProtoMessage() {}

func (x *RequestJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJobsRequest.ProtoReflect.Descriptor instead.
func (*RequestJobsRequest) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{0}
}

func (x *RequestJobsRequest) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RequestJobsRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type AssignedJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignedJob) Reset() {
	*x = AssignedJob{}
	mi := &file_services_job_execution_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedJob) ProtoMessage() {}

func (x *AssignedJob) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedJob.ProtoReflect.Descriptor instead.
func (*AssignedJob) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AssignedJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssignedJob) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type RequestJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*AssignedJob         `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestJobsResponse) Reset() {
	*x = RequestJobsResponse{}
	mi := &file_services_job_execution_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJobsResponse) ProtoMessage() {}

func (x *RequestJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJobsResponse.ProtoReflect.Descriptor instead.
func (*RequestJobsResponse) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{2}
}

func (x *RequestJobsResponse) GetJobs() []*AssignedJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type ResolveJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveJobRequest) Reset() {
	*x = ResolveJobRequest{}
	mi := &file_services_job_execution_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveJobRequest) ProtoMessage() {}

func (x *ResolveJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveJobRequest.ProtoReflect.Descriptor instead.
func (*ResolveJobRequest) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResolveJobRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type ResolveJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       *Project               `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Workflow      *Workflow              `protobuf:"bytes,4,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Revision      *Revision              `protobuf:"bytes,5,opt,name=revision,proto3" json:"revision,omitempty"`
	Vars          map[string]string      `protobuf:"bytes,6,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Secrets       map[string]string      `protobuf:"bytes,7,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Env           map[string]string      `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Inputs        map[string]*InputValue `protobuf:"bytes,9,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Steps         []*Step                `protobuf:"bytes,10,rep,name=steps,proto3" json:"steps,omitempty"`
	ScanHistories map[string]*ScanMeta   `protobuf:"bytes,11,rep,name=scan_histories,json=scanHistories,proto3" json:"scan_histories,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveJobResponse) Reset() {
	*x = ResolveJobResponse{}
	mi := &file_services_job_execution_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveJobResponse) ProtoMessage() {}

func (x *ResolveJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveJobResponse.ProtoReflect.Descriptor instead.
func (*ResolveJobResponse) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveJobResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResolveJobResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveJobResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ResolveJobResponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *ResolveJobResponse) GetRevision() *Revision {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *ResolveJobResponse) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *ResolveJobResponse) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ResolveJobResponse) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ResolveJobResponse) GetInputs() map[string]*InputValue {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ResolveJobResponse) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ResolveJobResponse) GetScanHistories() map[string]*ScanMeta {
	if x != nil {
		return x.ScanHistories
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_services_job_execution_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{5}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_services_job_execution_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{6}
}

func (x *Workflow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Revision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revision) Reset() {
	*x = Revision{}
	mi := &file_services_job_execution_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revision) ProtoMessage() {}

func (x *Revision) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revision.ProtoReflect.Descriptor instead.
func (*Revision) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{7}
}

func (x *Revision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Step struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Step:
	//
	//	*Step_Setup
	//	*Step_Command
	//	*Step_Artifact
	//	*Step_Teardown
	Step          isStep_Step `protobuf_oneof:"step"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_services_job_execution_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{8}
}

func (x *Step) GetStep() isStep_Step {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *Step) GetSetup() *SetupStep {
	if x != nil {
		if x, ok := x.Step.(*Step_Setup); ok {
			return x.Setup
		}
	}
	return nil
}

func (x *Step) GetCommand() *CommandStep {
	if x != nil {
		if x, ok := x.Step.(*Step_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Step) GetArtifact() *ArtifactSteps {
	if x != nil {
		if x, ok := x.Step.(*Step_Artifact); ok {
			return x.Artifact
		}
	}
	return nil
}

func (x *Step) GetTeardown() *TeardownStep {
	if x != nil {
		if x, ok := x.Step.(*Step_Teardown); ok {
			return x.Teardown
		}
	}
	return nil
}

type isStep_Step interface {
	isStep_Step()
}

type Step_Setup struct {
	Setup *SetupStep `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}

type Step_Command struct {
	Command *CommandStep `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type Step_Artifact struct {
	Artifact *ArtifactSteps `protobuf:"bytes,3,opt,name=artifact,proto3,oneof"`
}

type Step_Teardown struct {
	Teardown *TeardownStep `protobuf:"bytes,4,opt,name=teardown,proto3,oneof"`
}

func (*Step_Setup) isStep_Step() {}

func (*Step_Command) isStep_Step() {}

func (*Step_Artifact) isStep_Step() {}

func (*Step_Teardown) isStep_Step() {}

type SetupStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupStep) Reset() {
	*x = SetupStep{}
	mi := &file_services_job_execution_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupStep) ProtoMessage() {}

func (x *SetupStep) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupStep.ProtoReflect.Descriptor instead.
func (*SetupStep) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{9}
}

type CommandStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           string                 `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	Shell         string                 `protobuf:"bytes,2,opt,name=shell,proto3" json:"shell,omitempty"`
	Cond          string                 `protobuf:"bytes,3,opt,name=cond,proto3" json:"cond,omitempty"`
	AllowFailure  bool                   `protobuf:"varint,4,opt,name=allow_failure,json=allowFailure,proto3" json:"allow_failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandStep) Reset() {
	*x = CommandStep{}
	mi := &file_services_job_execution_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStep) ProtoMessage() {}

func (x *CommandStep) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStep.ProtoReflect.Descriptor instead.
func (*CommandStep) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{10}
}

func (x *CommandStep) GetRun() string {
	if x != nil {
		return x.Run
	}
	return ""
}

func (x *CommandStep) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *CommandStep) GetCond() string {
	if x != nil {
		return x.Cond
	}
	return ""
}

func (x *CommandStep) GetAllowFailure() bool {
	if x != nil {
		return x.AllowFailure
	}
	return false
}

type ArtifactSteps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*ArtifactStep        `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactSteps) Reset() {
	*x = ArtifactSteps{}
	mi := &file_services_job_execution_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactSteps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactSteps) ProtoMessage() {}

func (x *ArtifactSteps) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactSteps.ProtoReflect.Descriptor instead.
func (*ArtifactSteps) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{11}
}

func (x *ArtifactSteps) GetArtifacts() []*ArtifactStep {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ArtifactStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	Cond          string                 `protobuf:"bytes,3,opt,name=cond,proto3" json:"cond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactStep) Reset() {
	*x = ArtifactStep{}
	mi := &file_services_job_execution_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactStep) ProtoMessage() {}

func (x *ArtifactStep) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactStep.ProtoReflect.Descriptor instead.
func (*ArtifactStep) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{12}
}

func (x *ArtifactStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactStep) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *ArtifactStep) GetCond() string {
	if x != nil {
		return x.Cond
	}
	return ""
}

type TeardownStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownStep) Reset() {
	*x = TeardownStep{}
	mi := &file_services_job_execution_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownStep) ProtoMessage() {}

func (x *TeardownStep) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownStep.ProtoReflect.Descriptor instead.
func (*TeardownStep) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{13}
}

type InputValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*InputValue_String_
	//	*InputValue_Bool
	Value         isInputValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputValue) Reset() {
	*x = InputValue{}
	mi := &file_services_job_execution_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputValue) ProtoMessage() {}

func (x *InputValue) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputValue.ProtoReflect.Descriptor instead.
func (*InputValue) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{14}
}

func (x *InputValue) GetValue() isInputValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *InputValue) GetString_() string {
	if x != nil {
		if x, ok := x.Value.(*InputValue_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *InputValue) GetBool() bool {
	if x != nil {
		if x, ok := x.Value.(*InputValue_Bool); ok {
			return x.Bool
		}
	}
	return false
}

type isInputValue_Value interface {
	isInputValue_Value()
}

type InputValue_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type InputValue_Bool struct {
	Bool bool `protobuf:"varint,2,opt,name=bool,proto3,oneof"`
}

func (*InputValue_String_) isInputValue_Value() {}

func (*InputValue_Bool) isInputValue_Value() {}

type ScanMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobMeta             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanMeta) Reset() {
	*x = ScanMeta{}
	mi := &file_services_job_execution_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanMeta) ProtoMessage() {}

func (x *ScanMeta) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanMeta.ProtoReflect.Descriptor instead.
func (*ScanMeta) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{15}
}

func (x *ScanMeta) GetJobs() []*JobMeta {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type JobMeta struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Outcome       JobOutcome               `protobuf:"varint,2,opt,name=outcome,proto3,enum=bountyhub.job.execution.v1.JobOutcome" json:"outcome,omitempty"`
	Artifacts     map[string]*ArtifactMeta `protobuf:"bytes,3,rep,name=artifacts,proto3" json:"artifacts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobMeta) Reset() {
	*x = JobMeta{}
	mi := &file_services_job_execution_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobMeta) ProtoMessage() {}

func (x *JobMeta) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobMeta.ProtoReflect.Descriptor instead.
func (*JobMeta) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{16}
}

func (x *JobMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobMeta) GetOutcome() JobOutcome {
	if x != nil {
		return x.Outcome
	}
	return JobOutcome_JOB_OUTCOME_UNSPECIFIED
}

func (x *JobMeta) GetArtifacts() map[string]*ArtifactMeta {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ArtifactMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasDiff       bool                   `protobuf:"varint,1,opt,name=has_diff,json=hasDiff,proto3" json:"has_diff,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,2,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactMeta) Reset() {
	*x = ArtifactMeta{}
	mi := &file_services_job_execution_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactMeta) ProtoMessage() {}

func (x *ArtifactMeta) ProtoReflect() protoreflect.Message {
	mi := &file_services_job_execution_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactMeta.ProtoReflect.Descriptor instead.
func (*ArtifactMeta) Descriptor() ([]byte, []int) {
	return file_services_job_execution_v1_proto_rawDescGZIP(), []int{17}
}

func (x *ArtifactMeta) GetHasDiff() bool {
	if x != nil {
		return x.HasDiff
	}
	return false
}

func (x *ArtifactMeta) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_services_job_execution_v1_proto protoreflect.FileDescriptor

const file_services_job_execution_v1_proto_rawDesc = "" +
	"\n" +
	"\x1fservices/job_execution_v1.proto\x12\x1abountyhub.job.execution.v1\x1a\x1cgoogle/api/annotations.proto\"J\n" +
	"\x12RequestJobsRequest\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x04R\bcapacity\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\"7\n" +
	"\vAssignedJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\"R\n" +
	"\x13RequestJobsResponse\x12;\n" +
	"\x04jobs\x18\x01 \x03(\v2'.bountyhub.job.execution.v1.AssignedJobR\x04jobs\"=\n" +
	"\x11ResolveJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\"\xd9\b\n" +
	"\x12ResolveJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12=\n" +
	"\aproject\x18\x03 \x01(\v2#.bountyhub.job.execution.v1.ProjectR\aproject\x12@\n" +
	"\bworkflow\x18\x04 \x01(\v2$.bountyhub.job.execution.v1.WorkflowR\bworkflow\x12@\n" +
	"\brevision\x18\x05 \x01(\v2$.bountyhub.job.execution.v1.RevisionR\brevision\x12L\n" +
	"\x04vars\x18\x06 \x03(\v28.bountyhub.job.execution.v1.ResolveJobResponse.VarsEntryR\x04vars\x12U\n" +
	"\asecrets\x18\a \x03(\v2;.bountyhub.job.execution.v1.ResolveJobResponse.SecretsEntryR\asecrets\x12I\n" +
	"\x03env\x18\b \x03(\v27.bountyhub.job.execution.v1.ResolveJobResponse.EnvEntryR\x03env\x12R\n" +
	"\x06inputs\x18\t \x03(\v2:.bountyhub.job.execution.v1.ResolveJobResponse.InputsEntryR\x06inputs\x126\n" +
	"\x05steps\x18\n" +
	" \x03(\v2 .bountyhub.job.execution.v1.StepR\x05steps\x12h\n" +
	"\x0escan_histories\x18\v \x03(\v2A.bountyhub.job.execution.v1.ResolveJobResponse.ScanHistoriesEntryR\rscanHistories\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aa\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.bountyhub.job.execution.v1.InputValueR\x05value:\x028\x01\x1af\n" +
	"\x12ScanHistoriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.bountyhub.job.execution.v1.ScanMetaR\x05value:\x028\x01\"\x19\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\bWorkflow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\bRevision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa3\x02\n" +
	"\x04Step\x12=\n" +
	"\x05setup\x18\x01 \x01(\v2%.bountyhub.job.execution.v1.SetupStepH\x00R\x05setup\x12C\n" +
	"\acommand\x18\x02 \x01(\v2'.bountyhub.job.execution.v1.CommandStepH\x00R\acommand\x12G\n" +
	"\bartifact\x18\x03 \x01(\v2).bountyhub.job.execution.v1.ArtifactStepsH\x00R\bartifact\x12F\n" +
	"\bteardown\x18\x04 \x01(\v2(.bountyhub.job.execution.v1.TeardownStepH\x00R\bteardownB\x06\n" +
	"\x04step\"\v\n" +
	"\tSetupStep\"n\n" +
	"\vCommandStep\x12\x10\n" +
	"\x03run\x18\x01 \x01(\tR\x03run\x12\x14\n" +
	"\x05shell\x18\x02 \x01(\tR\x05shell\x12\x12\n" +
	"\x04cond\x18\x03 \x01(\tR\x04cond\x12#\n" +
	"\rallow_failure\x18\x04 \x01(\bR\fallowFailure\"W\n" +
	"\rArtifactSteps\x12F\n" +
	"\tartifacts\x18\x01 \x03(\v2(.bountyhub.job.execution.v1.ArtifactStepR\tartifacts\"L\n" +
	"\fArtifactStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\x12\x12\n" +
	"\x04cond\x18\x03 \x01(\tR\x04cond\"\x0e\n" +
	"\fTeardownStep\"E\n" +
	"\n" +
	"InputValue\x12\x18\n" +
	"\x06string\x18\x01 \x01(\tH\x00R\x06string\x12\x14\n" +
	"\x04bool\x18\x02 \x01(\bH\x00R\x04boolB\a\n" +
	"\x05value\"C\n" +
	"\bScanMeta\x127\n" +
	"\x04jobs\x18\x01 \x03(\v2#.bountyhub.job.execution.v1.JobMetaR\x04jobs\"\x95\x02\n" +
	"\aJobMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\aoutcome\x18\x02 \x01(\x0e2&.bountyhub.job.execution.v1.JobOutcomeR\aoutcome\x12P\n" +
	"\tartifacts\x18\x03 \x03(\v22.bountyhub.job.execution.v1.JobMeta.ArtifactsEntryR\tartifacts\x1af\n" +
	"\x0eArtifactsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.bountyhub.job.execution.v1.ArtifactMetaR\x05value:\x028\x01\"L\n" +
	"\fArtifactMeta\x12\x19\n" +
	"\bhas_diff\x18\x01 \x01(\bR\ahasDiff\x12!\n" +
	"\fis_available\x18\x02 \x01(\bR\visAvailable*v\n" +
	"\n" +
	"JobOutcome\x12\x1b\n" +
	"\x17JOB_OUTCOME_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13JOB_OUTCOME_SUCCESS\x10\x01\x12\x17\n" +
	"\x13JOB_OUTCOME_FAILURE\x10\x02\x12\x19\n" +
	"\x15JOB_OUTCOME_CANCELLED\x10\x032\xbc\x02\n" +
	"\x13JobExecutionService\x12\x92\x01\n" +
	"\vRequestJobs\x12..bountyhub.job.execution.v1.RequestJobsRequest\x1a/.bountyhub.job.execution.v1.RequestJobsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\"\x1a/v1/job-executions/request\x12\x8f\x01\n" +
	"\n" +
	"ResolveJob\x12-.bountyhub.job.execution.v1.ResolveJobRequest\x1a..bountyhub.job.execution.v1.ResolveJobResponse\"\"\x82\xd3\xe4\x93\x02\x1c\"\x1a/v1/job-executions/resolveBVZTgithub.com/bountyhub-org/bountyhub/internal/connectrpc/service/jobexecutionv1connectb\x06proto3"

var (
	file_services_job_execution_v1_proto_rawDescOnce sync.Once
	file_services_job_execution_v1_proto_rawDescData []byte
)

func file_services_job_execution_v1_proto_rawDescGZIP() []byte {
	file_services_job_execution_v1_proto_rawDescOnce.Do(func() {
		file_services_job_execution_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_job_execution_v1_proto_rawDesc), len(file_services_job_execution_v1_proto_rawDesc)))
	})
	return file_services_job_execution_v1_proto_rawDescData
}

var file_services_job_execution_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_job_execution_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_services_job_execution_v1_proto_goTypes = []any{
	(JobOutcome)(0),             // 0: bountyhub.job.execution.v1.JobOutcome
	(*RequestJobsRequest)(nil),  // 1: bountyhub.job.execution.v1.RequestJobsRequest
	(*AssignedJob)(nil),         // 2: bountyhub.job.execution.v1.AssignedJob
	(*RequestJobsResponse)(nil), // 3: bountyhub.job.execution.v1.RequestJobsResponse
	(*ResolveJobRequest)(nil),   // 4: bountyhub.job.execution.v1.ResolveJobRequest
	(*ResolveJobResponse)(nil),  // 5: bountyhub.job.execution.v1.ResolveJobResponse
	(*Project)(nil),             // 6: bountyhub.job.execution.v1.Project
	(*Workflow)(nil),            // 7: bountyhub.job.execution.v1.Workflow
	(*Revision)(nil),            // 8: bountyhub.job.execution.v1.Revision
	(*Step)(nil),                // 9: bountyhub.job.execution.v1.Step
	(*SetupStep)(nil),           // 10: bountyhub.job.execution.v1.SetupStep
	(*CommandStep)(nil),         // 11: bountyhub.job.execution.v1.CommandStep
	(*ArtifactSteps)(nil),       // 12: bountyhub.job.execution.v1.ArtifactSteps
	(*ArtifactStep)(nil),        // 13: bountyhub.job.execution.v1.ArtifactStep
	(*TeardownStep)(nil),        // 14: bountyhub.job.execution.v1.TeardownStep
	(*InputValue)(nil),          // 15: bountyhub.job.execution.v1.InputValue
	(*ScanMeta)(nil),            // 16: bountyhub.job.execution.v1.ScanMeta
	(*JobMeta)(nil),             // 17: bountyhub.job.execution.v1.JobMeta
	(*ArtifactMeta)(nil),        // 18: bountyhub.job.execution.v1.ArtifactMeta
	nil,                         // 19: bountyhub.job.execution.v1.ResolveJobResponse.VarsEntry
	nil,                         // 20: bountyhub.job.execution.v1.ResolveJobResponse.SecretsEntry
	nil,                         // 21: bountyhub.job.execution.v1.ResolveJobResponse.EnvEntry
	nil,                         // 22: bountyhub.job.execution.v1.ResolveJobResponse.InputsEntry
	nil,                         // 23: bountyhub.job.execution.v1.ResolveJobResponse.ScanHistoriesEntry
	nil,                         // 24: bountyhub.job.execution.v1.JobMeta.ArtifactsEntry
}
var file_services_job_execution_v1_proto_depIdxs = []int32{
	2,  // 0: bountyhub.job.execution.v1.RequestJobsResponse.jobs:type_name -> bountyhub.job.execution.v1.AssignedJob
	6,  // 1: bountyhub.job.execution.v1.ResolveJobResponse.project:type_name -> bountyhub.job.execution.v1.Project
	7,  // 2: bountyhub.job.execution.v1.ResolveJobResponse.workflow:type_name -> bountyhub.job.execution.v1.Workflow
	8,  // 3: bountyhub.job.execution.v1.ResolveJobResponse.revision:type_name -> bountyhub.job.execution.v1.Revision
	19, // 4: bountyhub.job.execution.v1.ResolveJobResponse.vars:type_name -> bountyhub.job.execution.v1.ResolveJobResponse.VarsEntry
	20, // 5: bountyhub.job.execution.v1.ResolveJobResponse.secrets:type_name -> bountyhub.job.execution.v1.ResolveJobResponse.SecretsEntry
	21, // 6: bountyhub.job.execution.v1.ResolveJobResponse.env:type_name -> bountyhub.job.execution.v1.ResolveJobResponse.EnvEntry
	22, // 7: bountyhub.job.execution.v1.ResolveJobResponse.inputs:type_name -> bountyhub.job.execution.v1.ResolveJobResponse.InputsEntry
	9,  // 8: bountyhub.job.execution.v1.ResolveJobResponse.steps:type_name -> bountyhub.job.execution.v1.Step
	23, // 9: bountyhub.job.execution.v1.ResolveJobResponse.scan_histories:type_name -> bountyhub.job.execution.v1.ResolveJobResponse.ScanHistoriesEntry
	10, // 10: bountyhub.job.execution.v1.Step.setup:type_name -> bountyhub.job.execution.v1.SetupStep
	11, // 11: bountyhub.job.execution.v1.Step.command:type_name -> bountyhub.job.execution.v1.CommandStep
	12, // 12: bountyhub.job.execution.v1.Step.artifact:type_name -> bountyhub.job.execution.v1.ArtifactSteps
	14, // 13: bountyhub.job.execution.v1.Step.teardown:type_name -> bountyhub.job.execution.v1.TeardownStep
	13, // 14: bountyhub.job.execution.v1.ArtifactSteps.artifacts:type_name -> bountyhub.job.execution.v1.ArtifactStep
	17, // 15: bountyhub.job.execution.v1.ScanMeta.jobs:type_name -> bountyhub.job.execution.v1.JobMeta
	0,  // 16: bountyhub.job.execution.v1.JobMeta.outcome:type_name -> bountyhub.job.execution.v1.JobOutcome
	24, // 17: bountyhub.job.execution.v1.JobMeta.artifacts:type_name -> bountyhub.job.execution.v1.JobMeta.ArtifactsEntry
	15, // 18: bountyhub.job.execution.v1.ResolveJobResponse.InputsEntry.value:type_name -> bountyhub.job.execution.v1.InputValue
	16, // 19: bountyhub.job.execution.v1.ResolveJobResponse.ScanHistoriesEntry.value:type_name -> bountyhub.job.execution.v1.ScanMeta
	18, // 20: bountyhub.job.execution.v1.JobMeta.ArtifactsEntry.value:type_name -> bountyhub.job.execution.v1.ArtifactMeta
	1,  // 21: bountyhub.job.execution.v1.JobExecutionService.RequestJobs:input_type -> bountyhub.job.execution.v1.RequestJobsRequest
	4,  // 22: bountyhub.job.execution.v1.JobExecutionService.ResolveJob:input_type -> bountyhub.job.execution.v1.ResolveJobRequest
	3,  // 23: bountyhub.job.execution.v1.JobExecutionService.RequestJobs:output_type -> bountyhub.job.execution.v1.RequestJobsResponse
	5,  // 24: bountyhub.job.execution.v1.JobExecutionService.ResolveJob:output_type -> bountyhub.job.execution.v1.ResolveJobResponse
	23, // [23:25] is the sub-list for method output_type
	21, // [21:23] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_services_job_execution_v1_proto_init() }
func file_services_job_execution_v1_proto_init() {
	if File_services_job_execution_v1_proto != nil {
		return
	}
	file_services_job_execution_v1_proto_msgTypes[8].OneofWrappers = []any{
		(*Step_Setup)(nil),
		(*Step_Command)(nil),
		(*Step_Artifact)(nil),
		(*Step_Teardown)(nil),
	}
	file_services_job_execution_v1_proto_msgTypes[14].OneofWrappers = []any{
		(*InputValue_String_)(nil),
		(*InputValue_Bool)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_job_execution_v1_proto_rawDesc), len(file_services_job_execution_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_job_execution_v1_proto_goTypes,
		DependencyIndexes: file_services_job_execution_v1_proto_depIdxs,
		EnumInfos:         file_services_job_execution_v1_proto_enumTypes,
		MessageInfos:      file_services_job_execution_v1_proto_msgTypes,
	}.Build()
	File_services_job_execution_v1_proto = out.File
	file_services_job_execution_v1_proto_goTypes = nil
	file_services_job_execution_v1_proto_depIdxs = nil
}
