// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/job_execution_v1.proto

package jobexecutionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// JobExecutionServiceName is the fully-qualified name of the JobExecutionService service.
	JobExecutionServiceName = "bountyhub.job.execution.v1.JobExecutionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// JobExecutionServiceRequestJobsProcedure is the fully-qualified name of the JobExecutionService's
	// RequestJobs RPC.
	JobExecutionServiceRequestJobsProcedure = "/bountyhub.job.execution.v1.JobExecutionService/RequestJobs"
	// JobExecutionServiceResolveJobProcedure is the fully-qualified name of the JobExecutionService's
	// ResolveJob RPC.
	JobExecutionServiceResolveJobProcedure = "/bountyhub.job.execution.v1.JobExecutionService/ResolveJob"
)

// JobExecutionServiceClient is a client for the bountyhub.job.execution.v1.JobExecutionService
// service.
type JobExecutionServiceClient interface {
	RequestJobs(context.Context, *connect.Request[RequestJobsRequest]) (*connect.Response[RequestJobsResponse], error)
	ResolveJob(context.Context, *connect.Request[ResolveJobRequest]) (*connect.Response[ResolveJobResponse], error)
}

// NewJobExecutionServiceClient constructs a client for the
// bountyhub.job.execution.v1.JobExecutionService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewJobExecutionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) JobExecutionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	jobExecutionServiceMethods := File_services_job_execution_v1_proto.Services().ByName("JobExecutionService").Methods()
	return &jobExecutionServiceClient{
		requestJobs: connect.NewClient[RequestJobsRequest, RequestJobsResponse](
			httpClient,
			baseURL+JobExecutionServiceRequestJobsProcedure,
			connect.WithSchema(jobExecutionServiceMethods.ByName("RequestJobs")),
			connect.WithClientOptions(opts...),
		),
		resolveJob: connect.NewClient[ResolveJobRequest, ResolveJobResponse](
			httpClient,
			baseURL+JobExecutionServiceResolveJobProcedure,
			connect.WithSchema(jobExecutionServiceMethods.ByName("ResolveJob")),
			connect.WithClientOptions(opts...),
		),
	}
}

// jobExecutionServiceClient implements JobExecutionServiceClient.
type jobExecutionServiceClient struct {
	requestJobs *connect.Client[RequestJobsRequest, RequestJobsResponse]
	resolveJob  *connect.Client[ResolveJobRequest, ResolveJobResponse]
}

// RequestJobs calls bountyhub.job.execution.v1.JobExecutionService.RequestJobs.
func (c *jobExecutionServiceClient) RequestJobs(ctx context.Context, req *connect.Request[RequestJobsRequest]) (*connect.Response[RequestJobsResponse], error) {
	return c.requestJobs.CallUnary(ctx, req)
}

// ResolveJob calls bountyhub.job.execution.v1.JobExecutionService.ResolveJob.
func (c *jobExecutionServiceClient) ResolveJob(ctx context.Context, req *connect.Request[ResolveJobRequest]) (*connect.Response[ResolveJobResponse], error) {
	return c.resolveJob.CallUnary(ctx, req)
}

// JobExecutionServiceHandler is an implementation of the
// bountyhub.job.execution.v1.JobExecutionService service.
type JobExecutionServiceHandler interface {
	RequestJobs(context.Context, *connect.Request[RequestJobsRequest]) (*connect.Response[RequestJobsResponse], error)
	ResolveJob(context.Context, *connect.Request[ResolveJobRequest]) (*connect.Response[ResolveJobResponse], error)
}

// NewJobExecutionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewJobExecutionServiceHandler(svc JobExecutionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	jobExecutionServiceMethods := File_services_job_execution_v1_proto.Services().ByName("JobExecutionService").Methods()
	jobExecutionServiceRequestJobsHandler := connect.NewUnaryHandler(
		JobExecutionServiceRequestJobsProcedure,
		svc.RequestJobs,
		connect.WithSchema(jobExecutionServiceMethods.ByName("RequestJobs")),
		connect.WithHandlerOptions(opts...),
	)
	jobExecutionServiceResolveJobHandler := connect.NewUnaryHandler(
		JobExecutionServiceResolveJobProcedure,
		svc.ResolveJob,
		connect.WithSchema(jobExecutionServiceMethods.ByName("ResolveJob")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bountyhub.job.execution.v1.JobExecutionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case JobExecutionServiceRequestJobsProcedure:
			jobExecutionServiceRequestJobsHandler.ServeHTTP(w, r)
		case JobExecutionServiceResolveJobProcedure:
			jobExecutionServiceResolveJobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedJobExecutionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedJobExecutionServiceHandler struct{}

func (UnimplementedJobExecutionServiceHandler) RequestJobs(context.Context, *connect.Request[RequestJobsRequest]) (*connect.Response[RequestJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bountyhub.job.execution.v1.JobExecutionService.RequestJobs is not implemented"))
}

func (UnimplementedJobExecutionServiceHandler) ResolveJob(context.Context, *connect.Request[ResolveJobRequest]) (*connect.Response[ResolveJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bountyhub.job.execution.v1.JobExecutionService.ResolveJob is not implemented"))
}
