// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: job_execution_v1.proto

package jobexecutionv1connect

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StepStatus int32

const (
	StepStatus_STEP_STATUS_UNSPECIFIED StepStatus = 0
	StepStatus_STEP_STATUS_SUCCEEDED   StepStatus = 1
	StepStatus_STEP_STATUS_FAILED      StepStatus = 2
	StepStatus_STEP_STATUS_SKIPPED     StepStatus = 3
)

// Enum value maps for StepStatus.
var (
	StepStatus_name = map[int32]string{
		0: "STEP_STATUS_UNSPECIFIED",
		1: "STEP_STATUS_SUCCEEDED",
		2: "STEP_STATUS_FAILED",
		3: "STEP_STATUS_SKIPPED",
	}
	StepStatus_value = map[string]int32{
		"STEP_STATUS_UNSPECIFIED": 0,
		"STEP_STATUS_SUCCEEDED":   1,
		"STEP_STATUS_FAILED":      2,
		"STEP_STATUS_SKIPPED":     3,
	}
)

func (x StepStatus) Enum() *StepStatus {
	p := new(StepStatus)
	*p = x
	return p
}

func (x StepStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_job_execution_v1_proto_enumTypes[0].Descriptor()
}

func (StepStatus) Type() protoreflect.EnumType {
	return &file_job_execution_v1_proto_enumTypes[0]
}

func (x StepStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepStatus.Descriptor instead.
func (StepStatus) EnumDescriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{0}
}

type StepOutcome int32

const (
	StepOutcome_STEP_OUTCOME_UNSPECIFIED StepOutcome = 0
	StepOutcome_STEP_OUTCOME_SUCCEEDED   StepOutcome = 1
	StepOutcome_STEP_OUTCOME_FAILED      StepOutcome = 2
	StepOutcome_STEP_OUTCOME_CANCELLED   StepOutcome = 3
)

// Enum value maps for StepOutcome.
var (
	StepOutcome_name = map[int32]string{
		0: "STEP_OUTCOME_UNSPECIFIED",
		1: "STEP_OUTCOME_SUCCEEDED",
		2: "STEP_OUTCOME_FAILED",
		3: "STEP_OUTCOME_CANCELLED",
	}
	StepOutcome_value = map[string]int32{
		"STEP_OUTCOME_UNSPECIFIED": 0,
		"STEP_OUTCOME_SUCCEEDED":   1,
		"STEP_OUTCOME_FAILED":      2,
		"STEP_OUTCOME_CANCELLED":   3,
	}
)

func (x StepOutcome) Enum() *StepOutcome {
	p := new(StepOutcome)
	*p = x
	return p
}

func (x StepOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_job_execution_v1_proto_enumTypes[1].Descriptor()
}

func (StepOutcome) Type() protoreflect.EnumType {
	return &file_job_execution_v1_proto_enumTypes[1]
}

func (x StepOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepOutcome.Descriptor instead.
func (StepOutcome) EnumDescriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{1}
}

// Copy of bountyhub.job.v1.JobOutcome for use in JobExecutionService
// without importing the entire job.proto
type JobOutcome int32

const (
	JobOutcome_JOB_OUTCOME_UNSPECIFIED JobOutcome = 0
	JobOutcome_JOB_OUTCOME_SUCCEEDED   JobOutcome = 1
	JobOutcome_JOB_OUTCOME_FAILED      JobOutcome = 2
	JobOutcome_JOB_OUTCOME_CANCELLED   JobOutcome = 3
)

// Enum value maps for JobOutcome.
var (
	JobOutcome_name = map[int32]string{
		0: "JOB_OUTCOME_UNSPECIFIED",
		1: "JOB_OUTCOME_SUCCEEDED",
		2: "JOB_OUTCOME_FAILED",
		3: "JOB_OUTCOME_CANCELLED",
	}
	JobOutcome_value = map[string]int32{
		"JOB_OUTCOME_UNSPECIFIED": 0,
		"JOB_OUTCOME_SUCCEEDED":   1,
		"JOB_OUTCOME_FAILED":      2,
		"JOB_OUTCOME_CANCELLED":   3,
	}
)

func (x JobOutcome) Enum() *JobOutcome {
	p := new(JobOutcome)
	*p = x
	return p
}

func (x JobOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_job_execution_v1_proto_enumTypes[2].Descriptor()
}

func (JobOutcome) Type() protoreflect.EnumType {
	return &file_job_execution_v1_proto_enumTypes[2]
}

func (x JobOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobOutcome.Descriptor instead.
func (JobOutcome) EnumDescriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{2}
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Event         *JobEvent              `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_job_execution_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{0}
}

func (x *StreamEventsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StreamEventsRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *StreamEventsRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StreamEventsRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StreamEventsRequest) GetEvent() *JobEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type StreamEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	mi := &file_job_execution_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{1}
}

type JobEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*JobEvent_Started
	//	*JobEvent_Finished
	Event         isJobEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobEvent) Reset() {
	*x = JobEvent{}
	mi := &file_job_execution_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEvent) ProtoMessage() {}

func (x *JobEvent) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEvent.ProtoReflect.Descriptor instead.
func (*JobEvent) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{2}
}

func (x *JobEvent) GetEvent() isJobEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *JobEvent) GetStarted() *StepStarted {
	if x != nil {
		if x, ok := x.Event.(*JobEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *JobEvent) GetFinished() *StepFinished {
	if x != nil {
		if x, ok := x.Event.(*JobEvent_Finished); ok {
			return x.Finished
		}
	}
	return nil
}

type isJobEvent_Event interface {
	isJobEvent_Event()
}

type JobEvent_Started struct {
	Started *StepStarted `protobuf:"bytes,1,opt,name=started,proto3,oneof"`
}

type JobEvent_Finished struct {
	Finished *StepFinished `protobuf:"bytes,2,opt,name=finished,proto3,oneof"`
}

func (*JobEvent_Started) isJobEvent_Event() {}

func (*JobEvent_Finished) isJobEvent_Event() {}

type StepStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepStarted) Reset() {
	*x = StepStarted{}
	mi := &file_job_execution_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepStarted) ProtoMessage() {}

func (x *StepStarted) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepStarted.ProtoReflect.Descriptor instead.
func (*StepStarted) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{3}
}

func (x *StepStarted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StepFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        StepStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=bountyhub.job.execution.v1.StepStatus" json:"status,omitempty"`
	Outcome       StepOutcome            `protobuf:"varint,4,opt,name=outcome,proto3,enum=bountyhub.job.execution.v1.StepOutcome" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepFinished) Reset() {
	*x = StepFinished{}
	mi := &file_job_execution_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepFinished) ProtoMessage() {}

func (x *StepFinished) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepFinished.ProtoReflect.Descriptor instead.
func (*StepFinished) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{4}
}

func (x *StepFinished) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StepFinished) GetStatus() StepStatus {
	if x != nil {
		return x.Status
	}
	return StepStatus_STEP_STATUS_UNSPECIFIED
}

func (x *StepFinished) GetOutcome() StepOutcome {
	if x != nil {
		return x.Outcome
	}
	return StepOutcome_STEP_OUTCOME_UNSPECIFIED
}

type GetExecutionPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionPlanRequest) Reset() {
	*x = GetExecutionPlanRequest{}
	mi := &file_job_execution_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionPlanRequest) ProtoMessage() {}

func (x *GetExecutionPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionPlanRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionPlanRequest) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{5}
}

func (x *GetExecutionPlanRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetExecutionPlanRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type GetExecutionPlanRsponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       *Project               `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Workflow      *Workflow              `protobuf:"bytes,4,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Revision      *Revision              `protobuf:"bytes,5,opt,name=revision,proto3" json:"revision,omitempty"`
	Vars          map[string]string      `protobuf:"bytes,6,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Secrets       map[string]string      `protobuf:"bytes,7,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Env           map[string]string      `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Inputs        map[string]*InputValue `protobuf:"bytes,9,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Steps         []*Step                `protobuf:"bytes,10,rep,name=steps,proto3" json:"steps,omitempty"`
	ScanHistories map[string]*ScanMeta   `protobuf:"bytes,11,rep,name=scan_histories,json=scanHistories,proto3" json:"scan_histories,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionPlanRsponse) Reset() {
	*x = GetExecutionPlanRsponse{}
	mi := &file_job_execution_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionPlanRsponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionPlanRsponse) ProtoMessage() {}

func (x *GetExecutionPlanRsponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionPlanRsponse.ProtoReflect.Descriptor instead.
func (*GetExecutionPlanRsponse) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{6}
}

func (x *GetExecutionPlanRsponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetExecutionPlanRsponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetExecutionPlanRsponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *GetExecutionPlanRsponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *GetExecutionPlanRsponse) GetRevision() *Revision {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *GetExecutionPlanRsponse) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *GetExecutionPlanRsponse) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *GetExecutionPlanRsponse) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *GetExecutionPlanRsponse) GetInputs() map[string]*InputValue {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *GetExecutionPlanRsponse) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *GetExecutionPlanRsponse) GetScanHistories() map[string]*ScanMeta {
	if x != nil {
		return x.ScanHistories
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_job_execution_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{7}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_job_execution_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{8}
}

func (x *Workflow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Revision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revision) Reset() {
	*x = Revision{}
	mi := &file_job_execution_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revision) ProtoMessage() {}

func (x *Revision) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revision.ProtoReflect.Descriptor instead.
func (*Revision) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{9}
}

func (x *Revision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Step struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Step:
	//
	//	*Step_Setup
	//	*Step_Command
	//	*Step_Artifact
	//	*Step_Teardown
	Step          isStep_Step `protobuf_oneof:"step"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_job_execution_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{10}
}

func (x *Step) GetStep() isStep_Step {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *Step) GetSetup() *SetupStep {
	if x != nil {
		if x, ok := x.Step.(*Step_Setup); ok {
			return x.Setup
		}
	}
	return nil
}

func (x *Step) GetCommand() *CommandStep {
	if x != nil {
		if x, ok := x.Step.(*Step_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Step) GetArtifact() *ArtifactSteps {
	if x != nil {
		if x, ok := x.Step.(*Step_Artifact); ok {
			return x.Artifact
		}
	}
	return nil
}

func (x *Step) GetTeardown() *TeardownStep {
	if x != nil {
		if x, ok := x.Step.(*Step_Teardown); ok {
			return x.Teardown
		}
	}
	return nil
}

type isStep_Step interface {
	isStep_Step()
}

type Step_Setup struct {
	Setup *SetupStep `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}

type Step_Command struct {
	Command *CommandStep `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type Step_Artifact struct {
	Artifact *ArtifactSteps `protobuf:"bytes,3,opt,name=artifact,proto3,oneof"`
}

type Step_Teardown struct {
	Teardown *TeardownStep `protobuf:"bytes,4,opt,name=teardown,proto3,oneof"`
}

func (*Step_Setup) isStep_Step() {}

func (*Step_Command) isStep_Step() {}

func (*Step_Artifact) isStep_Step() {}

func (*Step_Teardown) isStep_Step() {}

type SetupStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupStep) Reset() {
	*x = SetupStep{}
	mi := &file_job_execution_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupStep) ProtoMessage() {}

func (x *SetupStep) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupStep.ProtoReflect.Descriptor instead.
func (*SetupStep) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{11}
}

type CommandStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           string                 `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	Shell         string                 `protobuf:"bytes,2,opt,name=shell,proto3" json:"shell,omitempty"`
	Cond          string                 `protobuf:"bytes,3,opt,name=cond,proto3" json:"cond,omitempty"`
	AllowFailure  bool                   `protobuf:"varint,4,opt,name=allow_failure,json=allowFailure,proto3" json:"allow_failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandStep) Reset() {
	*x = CommandStep{}
	mi := &file_job_execution_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStep) ProtoMessage() {}

func (x *CommandStep) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStep.ProtoReflect.Descriptor instead.
func (*CommandStep) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{12}
}

func (x *CommandStep) GetRun() string {
	if x != nil {
		return x.Run
	}
	return ""
}

func (x *CommandStep) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *CommandStep) GetCond() string {
	if x != nil {
		return x.Cond
	}
	return ""
}

func (x *CommandStep) GetAllowFailure() bool {
	if x != nil {
		return x.AllowFailure
	}
	return false
}

type ArtifactSteps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*ArtifactStep        `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactSteps) Reset() {
	*x = ArtifactSteps{}
	mi := &file_job_execution_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactSteps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactSteps) ProtoMessage() {}

func (x *ArtifactSteps) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactSteps.ProtoReflect.Descriptor instead.
func (*ArtifactSteps) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{13}
}

func (x *ArtifactSteps) GetArtifacts() []*ArtifactStep {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ArtifactStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	Cond          string                 `protobuf:"bytes,3,opt,name=cond,proto3" json:"cond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactStep) Reset() {
	*x = ArtifactStep{}
	mi := &file_job_execution_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactStep) ProtoMessage() {}

func (x *ArtifactStep) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactStep.ProtoReflect.Descriptor instead.
func (*ArtifactStep) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{14}
}

func (x *ArtifactStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactStep) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *ArtifactStep) GetCond() string {
	if x != nil {
		return x.Cond
	}
	return ""
}

type TeardownStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownStep) Reset() {
	*x = TeardownStep{}
	mi := &file_job_execution_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownStep) ProtoMessage() {}

func (x *TeardownStep) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownStep.ProtoReflect.Descriptor instead.
func (*TeardownStep) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{15}
}

type InputValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*InputValue_StringValue
	//	*InputValue_BoolValue
	Value         isInputValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputValue) Reset() {
	*x = InputValue{}
	mi := &file_job_execution_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputValue) ProtoMessage() {}

func (x *InputValue) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputValue.ProtoReflect.Descriptor instead.
func (*InputValue) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{16}
}

func (x *InputValue) GetValue() isInputValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *InputValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*InputValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *InputValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*InputValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isInputValue_Value interface {
	isInputValue_Value()
}

type InputValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type InputValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*InputValue_StringValue) isInputValue_Value() {}

func (*InputValue_BoolValue) isInputValue_Value() {}

type ScanMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobMeta             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanMeta) Reset() {
	*x = ScanMeta{}
	mi := &file_job_execution_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanMeta) ProtoMessage() {}

func (x *ScanMeta) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanMeta.ProtoReflect.Descriptor instead.
func (*ScanMeta) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{17}
}

func (x *ScanMeta) GetJobs() []*JobMeta {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type JobMeta struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Outcome       JobOutcome               `protobuf:"varint,2,opt,name=outcome,proto3,enum=bountyhub.job.execution.v1.JobOutcome" json:"outcome,omitempty"`
	Artifacts     map[string]*ArtifactMeta `protobuf:"bytes,3,rep,name=artifacts,proto3" json:"artifacts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobMeta) Reset() {
	*x = JobMeta{}
	mi := &file_job_execution_v1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobMeta) ProtoMessage() {}

func (x *JobMeta) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobMeta.ProtoReflect.Descriptor instead.
func (*JobMeta) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{18}
}

func (x *JobMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobMeta) GetOutcome() JobOutcome {
	if x != nil {
		return x.Outcome
	}
	return JobOutcome_JOB_OUTCOME_UNSPECIFIED
}

func (x *JobMeta) GetArtifacts() map[string]*ArtifactMeta {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ArtifactMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasDiff       bool                   `protobuf:"varint,1,opt,name=has_diff,json=hasDiff,proto3" json:"has_diff,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,2,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactMeta) Reset() {
	*x = ArtifactMeta{}
	mi := &file_job_execution_v1_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactMeta) ProtoMessage() {}

func (x *ArtifactMeta) ProtoReflect() protoreflect.Message {
	mi := &file_job_execution_v1_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactMeta.ProtoReflect.Descriptor instead.
func (*ArtifactMeta) Descriptor() ([]byte, []int) {
	return file_job_execution_v1_proto_rawDescGZIP(), []int{19}
}

func (x *ArtifactMeta) GetHasDiff() bool {
	if x != nil {
		return x.HasDiff
	}
	return false
}

func (x *ArtifactMeta) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_job_execution_v1_proto protoreflect.FileDescriptor

const file_job_execution_v1_proto_rawDesc = "" +
	"\n" +
	"\x16job_execution_v1.proto\x12\x1abountyhub.job.execution.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n" +
	"\x13StreamEventsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12:\n" +
	"\x05event\x18\x05 \x01(\v2$.bountyhub.job.execution.v1.JobEventR\x05event\"\x16\n" +
	"\x14StreamEventsResponse\"\xa0\x01\n" +
	"\bJobEvent\x12C\n" +
	"\astarted\x18\x01 \x01(\v2'.bountyhub.job.execution.v1.StepStartedH\x00R\astarted\x12F\n" +
	"\bfinished\x18\x02 \x01(\v2(.bountyhub.job.execution.v1.StepFinishedH\x00R\bfinishedB\a\n" +
	"\x05event\"\x1d\n" +
	"\vStepStarted\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x01\n" +
	"\fStepFinished\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\x06status\x18\x03 \x01(\x0e2&.bountyhub.job.execution.v1.StepStatusR\x06status\x12A\n" +
	"\aoutcome\x18\x04 \x01(\x0e2'.bountyhub.job.execution.v1.StepOutcomeR\aoutcome\"J\n" +
	"\x17GetExecutionPlanRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\"\xfe\b\n" +
	"\x17GetExecutionPlanRsponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12=\n" +
	"\aproject\x18\x03 \x01(\v2#.bountyhub.job.execution.v1.ProjectR\aproject\x12@\n" +
	"\bworkflow\x18\x04 \x01(\v2$.bountyhub.job.execution.v1.WorkflowR\bworkflow\x12@\n" +
	"\brevision\x18\x05 \x01(\v2$.bountyhub.job.execution.v1.RevisionR\brevision\x12Q\n" +
	"\x04vars\x18\x06 \x03(\v2=.bountyhub.job.execution.v1.GetExecutionPlanRsponse.VarsEntryR\x04vars\x12Z\n" +
	"\asecrets\x18\a \x03(\v2@.bountyhub.job.execution.v1.GetExecutionPlanRsponse.SecretsEntryR\asecrets\x12N\n" +
	"\x03env\x18\b \x03(\v2<.bountyhub.job.execution.v1.GetExecutionPlanRsponse.EnvEntryR\x03env\x12W\n" +
	"\x06inputs\x18\t \x03(\v2?.bountyhub.job.execution.v1.GetExecutionPlanRsponse.InputsEntryR\x06inputs\x126\n" +
	"\x05steps\x18\n" +
	" \x03(\v2 .bountyhub.job.execution.v1.StepR\x05steps\x12m\n" +
	"\x0escan_histories\x18\v \x03(\v2F.bountyhub.job.execution.v1.GetExecutionPlanRsponse.ScanHistoriesEntryR\rscanHistories\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aa\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.bountyhub.job.execution.v1.InputValueR\x05value:\x028\x01\x1af\n" +
	"\x12ScanHistoriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.bountyhub.job.execution.v1.ScanMetaR\x05value:\x028\x01\"\x19\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\bWorkflow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\bRevision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa3\x02\n" +
	"\x04Step\x12=\n" +
	"\x05setup\x18\x01 \x01(\v2%.bountyhub.job.execution.v1.SetupStepH\x00R\x05setup\x12C\n" +
	"\acommand\x18\x02 \x01(\v2'.bountyhub.job.execution.v1.CommandStepH\x00R\acommand\x12G\n" +
	"\bartifact\x18\x03 \x01(\v2).bountyhub.job.execution.v1.ArtifactStepsH\x00R\bartifact\x12F\n" +
	"\bteardown\x18\x04 \x01(\v2(.bountyhub.job.execution.v1.TeardownStepH\x00R\bteardownB\x06\n" +
	"\x04step\"\v\n" +
	"\tSetupStep\"n\n" +
	"\vCommandStep\x12\x10\n" +
	"\x03run\x18\x01 \x01(\tR\x03run\x12\x14\n" +
	"\x05shell\x18\x02 \x01(\tR\x05shell\x12\x12\n" +
	"\x04cond\x18\x03 \x01(\tR\x04cond\x12#\n" +
	"\rallow_failure\x18\x04 \x01(\bR\fallowFailure\"W\n" +
	"\rArtifactSteps\x12F\n" +
	"\tartifacts\x18\x01 \x03(\v2(.bountyhub.job.execution.v1.ArtifactStepR\tartifacts\"L\n" +
	"\fArtifactStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\x12\x12\n" +
	"\x04cond\x18\x03 \x01(\tR\x04cond\"\x0e\n" +
	"\fTeardownStep\"[\n" +
	"\n" +
	"InputValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\"C\n" +
	"\bScanMeta\x127\n" +
	"\x04jobs\x18\x01 \x03(\v2#.bountyhub.job.execution.v1.JobMetaR\x04jobs\"\x95\x02\n" +
	"\aJobMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\aoutcome\x18\x02 \x01(\x0e2&.bountyhub.job.execution.v1.JobOutcomeR\aoutcome\x12P\n" +
	"\tartifacts\x18\x03 \x03(\v22.bountyhub.job.execution.v1.JobMeta.ArtifactsEntryR\tartifacts\x1af\n" +
	"\x0eArtifactsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.bountyhub.job.execution.v1.ArtifactMetaR\x05value:\x028\x01\"L\n" +
	"\fArtifactMeta\x12\x19\n" +
	"\bhas_diff\x18\x01 \x01(\bR\ahasDiff\x12!\n" +
	"\fis_available\x18\x02 \x01(\bR\visAvailable*u\n" +
	"\n" +
	"StepStatus\x12\x1b\n" +
	"\x17STEP_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15STEP_STATUS_SUCCEEDED\x10\x01\x12\x16\n" +
	"\x12STEP_STATUS_FAILED\x10\x02\x12\x17\n" +
	"\x13STEP_STATUS_SKIPPED\x10\x03*|\n" +
	"\vStepOutcome\x12\x1c\n" +
	"\x18STEP_OUTCOME_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16STEP_OUTCOME_SUCCEEDED\x10\x01\x12\x17\n" +
	"\x13STEP_OUTCOME_FAILED\x10\x02\x12\x1a\n" +
	"\x16STEP_OUTCOME_CANCELLED\x10\x03*w\n" +
	"\n" +
	"JobOutcome\x12\x1b\n" +
	"\x17JOB_OUTCOME_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15JOB_OUTCOME_SUCCEEDED\x10\x01\x12\x16\n" +
	"\x12JOB_OUTCOME_FAILED\x10\x02\x12\x19\n" +
	"\x15JOB_OUTCOME_CANCELLED\x10\x032\xe0\x02\n" +
	"\x13JobExecutionService\x12\xa6\x01\n" +
	"\x10GetExecutionPlan\x123.bountyhub.job.execution.v1.GetExecutionPlanRequest\x1a3.bountyhub.job.execution.v1.GetExecutionPlanRsponse\"(\x82\xd3\xe4\x93\x02\"\" /v1/jobs/{job_id}/execution/plan\x12\x9f\x01\n" +
	"\fStreamEvents\x12/.bountyhub.job.execution.v1.StreamEventsRequest\x1a0.bountyhub.job.execution.v1.StreamEventsResponse\"*\x82\xd3\xe4\x93\x02$\"\"/v1/jobs/{job_id}/execution/events(\x01B\xfb\x01\n" +
	"\x1ecom.bountyhub.job.execution.v1B\x13JobExecutionV1ProtoP\x01Z9github.com/bountyhub-org/runner/api/jobexecutionv1connect\xa2\x02\x03BJE\xaa\x02\x1aBountyhub.Job.Execution.V1\xca\x02\x1aBountyhub\\Job\\Execution\\V1\xe2\x02&Bountyhub\\Job\\Execution\\V1\\GPBMetadata\xea\x02\x1dBountyhub::Job::Execution::V1b\x06proto3"

var (
	file_job_execution_v1_proto_rawDescOnce sync.Once
	file_job_execution_v1_proto_rawDescData []byte
)

func file_job_execution_v1_proto_rawDescGZIP() []byte {
	file_job_execution_v1_proto_rawDescOnce.Do(func() {
		file_job_execution_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_execution_v1_proto_rawDesc), len(file_job_execution_v1_proto_rawDesc)))
	})
	return file_job_execution_v1_proto_rawDescData
}

var file_job_execution_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_job_execution_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_job_execution_v1_proto_goTypes = []any{
	(StepStatus)(0),                 // 0: bountyhub.job.execution.v1.StepStatus
	(StepOutcome)(0),                // 1: bountyhub.job.execution.v1.StepOutcome
	(JobOutcome)(0),                 // 2: bountyhub.job.execution.v1.JobOutcome
	(*StreamEventsRequest)(nil),     // 3: bountyhub.job.execution.v1.StreamEventsRequest
	(*StreamEventsResponse)(nil),    // 4: bountyhub.job.execution.v1.StreamEventsResponse
	(*JobEvent)(nil),                // 5: bountyhub.job.execution.v1.JobEvent
	(*StepStarted)(nil),             // 6: bountyhub.job.execution.v1.StepStarted
	(*StepFinished)(nil),            // 7: bountyhub.job.execution.v1.StepFinished
	(*GetExecutionPlanRequest)(nil), // 8: bountyhub.job.execution.v1.GetExecutionPlanRequest
	(*GetExecutionPlanRsponse)(nil), // 9: bountyhub.job.execution.v1.GetExecutionPlanRsponse
	(*Project)(nil),                 // 10: bountyhub.job.execution.v1.Project
	(*Workflow)(nil),                // 11: bountyhub.job.execution.v1.Workflow
	(*Revision)(nil),                // 12: bountyhub.job.execution.v1.Revision
	(*Step)(nil),                    // 13: bountyhub.job.execution.v1.Step
	(*SetupStep)(nil),               // 14: bountyhub.job.execution.v1.SetupStep
	(*CommandStep)(nil),             // 15: bountyhub.job.execution.v1.CommandStep
	(*ArtifactSteps)(nil),           // 16: bountyhub.job.execution.v1.ArtifactSteps
	(*ArtifactStep)(nil),            // 17: bountyhub.job.execution.v1.ArtifactStep
	(*TeardownStep)(nil),            // 18: bountyhub.job.execution.v1.TeardownStep
	(*InputValue)(nil),              // 19: bountyhub.job.execution.v1.InputValue
	(*ScanMeta)(nil),                // 20: bountyhub.job.execution.v1.ScanMeta
	(*JobMeta)(nil),                 // 21: bountyhub.job.execution.v1.JobMeta
	(*ArtifactMeta)(nil),            // 22: bountyhub.job.execution.v1.ArtifactMeta
	nil,                             // 23: bountyhub.job.execution.v1.GetExecutionPlanRsponse.VarsEntry
	nil,                             // 24: bountyhub.job.execution.v1.GetExecutionPlanRsponse.SecretsEntry
	nil,                             // 25: bountyhub.job.execution.v1.GetExecutionPlanRsponse.EnvEntry
	nil,                             // 26: bountyhub.job.execution.v1.GetExecutionPlanRsponse.InputsEntry
	nil,                             // 27: bountyhub.job.execution.v1.GetExecutionPlanRsponse.ScanHistoriesEntry
	nil,                             // 28: bountyhub.job.execution.v1.JobMeta.ArtifactsEntry
	(*timestamppb.Timestamp)(nil),   // 29: google.protobuf.Timestamp
}
var file_job_execution_v1_proto_depIdxs = []int32{
	29, // 0: bountyhub.job.execution.v1.StreamEventsRequest.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 1: bountyhub.job.execution.v1.StreamEventsRequest.event:type_name -> bountyhub.job.execution.v1.JobEvent
	6,  // 2: bountyhub.job.execution.v1.JobEvent.started:type_name -> bountyhub.job.execution.v1.StepStarted
	7,  // 3: bountyhub.job.execution.v1.JobEvent.finished:type_name -> bountyhub.job.execution.v1.StepFinished
	0,  // 4: bountyhub.job.execution.v1.StepFinished.status:type_name -> bountyhub.job.execution.v1.StepStatus
	1,  // 5: bountyhub.job.execution.v1.StepFinished.outcome:type_name -> bountyhub.job.execution.v1.StepOutcome
	10, // 6: bountyhub.job.execution.v1.GetExecutionPlanRsponse.project:type_name -> bountyhub.job.execution.v1.Project
	11, // 7: bountyhub.job.execution.v1.GetExecutionPlanRsponse.workflow:type_name -> bountyhub.job.execution.v1.Workflow
	12, // 8: bountyhub.job.execution.v1.GetExecutionPlanRsponse.revision:type_name -> bountyhub.job.execution.v1.Revision
	23, // 9: bountyhub.job.execution.v1.GetExecutionPlanRsponse.vars:type_name -> bountyhub.job.execution.v1.GetExecutionPlanRsponse.VarsEntry
	24, // 10: bountyhub.job.execution.v1.GetExecutionPlanRsponse.secrets:type_name -> bountyhub.job.execution.v1.GetExecutionPlanRsponse.SecretsEntry
	25, // 11: bountyhub.job.execution.v1.GetExecutionPlanRsponse.env:type_name -> bountyhub.job.execution.v1.GetExecutionPlanRsponse.EnvEntry
	26, // 12: bountyhub.job.execution.v1.GetExecutionPlanRsponse.inputs:type_name -> bountyhub.job.execution.v1.GetExecutionPlanRsponse.InputsEntry
	13, // 13: bountyhub.job.execution.v1.GetExecutionPlanRsponse.steps:type_name -> bountyhub.job.execution.v1.Step
	27, // 14: bountyhub.job.execution.v1.GetExecutionPlanRsponse.scan_histories:type_name -> bountyhub.job.execution.v1.GetExecutionPlanRsponse.ScanHistoriesEntry
	14, // 15: bountyhub.job.execution.v1.Step.setup:type_name -> bountyhub.job.execution.v1.SetupStep
	15, // 16: bountyhub.job.execution.v1.Step.command:type_name -> bountyhub.job.execution.v1.CommandStep
	16, // 17: bountyhub.job.execution.v1.Step.artifact:type_name -> bountyhub.job.execution.v1.ArtifactSteps
	18, // 18: bountyhub.job.execution.v1.Step.teardown:type_name -> bountyhub.job.execution.v1.TeardownStep
	17, // 19: bountyhub.job.execution.v1.ArtifactSteps.artifacts:type_name -> bountyhub.job.execution.v1.ArtifactStep
	21, // 20: bountyhub.job.execution.v1.ScanMeta.jobs:type_name -> bountyhub.job.execution.v1.JobMeta
	2,  // 21: bountyhub.job.execution.v1.JobMeta.outcome:type_name -> bountyhub.job.execution.v1.JobOutcome
	28, // 22: bountyhub.job.execution.v1.JobMeta.artifacts:type_name -> bountyhub.job.execution.v1.JobMeta.ArtifactsEntry
	19, // 23: bountyhub.job.execution.v1.GetExecutionPlanRsponse.InputsEntry.value:type_name -> bountyhub.job.execution.v1.InputValue
	20, // 24: bountyhub.job.execution.v1.GetExecutionPlanRsponse.ScanHistoriesEntry.value:type_name -> bountyhub.job.execution.v1.ScanMeta
	22, // 25: bountyhub.job.execution.v1.JobMeta.ArtifactsEntry.value:type_name -> bountyhub.job.execution.v1.ArtifactMeta
	8,  // 26: bountyhub.job.execution.v1.JobExecutionService.GetExecutionPlan:input_type -> bountyhub.job.execution.v1.GetExecutionPlanRequest
	3,  // 27: bountyhub.job.execution.v1.JobExecutionService.StreamEvents:input_type -> bountyhub.job.execution.v1.StreamEventsRequest
	9,  // 28: bountyhub.job.execution.v1.JobExecutionService.GetExecutionPlan:output_type -> bountyhub.job.execution.v1.GetExecutionPlanRsponse
	4,  // 29: bountyhub.job.execution.v1.JobExecutionService.StreamEvents:output_type -> bountyhub.job.execution.v1.StreamEventsResponse
	28, // [28:30] is the sub-list for method output_type
	26, // [26:28] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_job_execution_v1_proto_init() }
func file_job_execution_v1_proto_init() {
	if File_job_execution_v1_proto != nil {
		return
	}
	file_job_execution_v1_proto_msgTypes[2].OneofWrappers = []any{
		(*JobEvent_Started)(nil),
		(*JobEvent_Finished)(nil),
	}
	file_job_execution_v1_proto_msgTypes[10].OneofWrappers = []any{
		(*Step_Setup)(nil),
		(*Step_Command)(nil),
		(*Step_Artifact)(nil),
		(*Step_Teardown)(nil),
	}
	file_job_execution_v1_proto_msgTypes[16].OneofWrappers = []any{
		(*InputValue_StringValue)(nil),
		(*InputValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_execution_v1_proto_rawDesc), len(file_job_execution_v1_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_execution_v1_proto_goTypes,
		DependencyIndexes: file_job_execution_v1_proto_depIdxs,
		EnumInfos:         file_job_execution_v1_proto_enumTypes,
		MessageInfos:      file_job_execution_v1_proto_msgTypes,
	}.Build()
	File_job_execution_v1_proto = out.File
	file_job_execution_v1_proto_goTypes = nil
	file_job_execution_v1_proto_depIdxs = nil
}
