// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: job_execution_v1.proto

package jobexecutionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// JobExecutionServiceName is the fully-qualified name of the JobExecutionService service.
	JobExecutionServiceName = "bountyhub.job.execution.v1.JobExecutionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// JobExecutionServiceAcquireExecutionProcedure is the fully-qualified name of the
	// JobExecutionService's AcquireExecution RPC.
	JobExecutionServiceAcquireExecutionProcedure = "/bountyhub.job.execution.v1.JobExecutionService/AcquireExecution"
	// JobExecutionServiceStreamEventsProcedure is the fully-qualified name of the JobExecutionService's
	// StreamEvents RPC.
	JobExecutionServiceStreamEventsProcedure = "/bountyhub.job.execution.v1.JobExecutionService/StreamEvents"
)

// JobExecutionServiceClient is a client for the bountyhub.job.execution.v1.JobExecutionService
// service.
type JobExecutionServiceClient interface {
	AcquireExecution(context.Context, *connect.Request[AcquireExecutionRequest]) (*connect.Response[AcquireExecutionResponse], error)
	StreamEvents(context.Context) *connect.ClientStreamForClient[StreamEventsRequest, StreamEventsResponse]
}

// NewJobExecutionServiceClient constructs a client for the
// bountyhub.job.execution.v1.JobExecutionService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewJobExecutionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) JobExecutionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	jobExecutionServiceMethods := File_job_execution_v1_proto.Services().ByName("JobExecutionService").Methods()
	return &jobExecutionServiceClient{
		acquireExecution: connect.NewClient[AcquireExecutionRequest, AcquireExecutionResponse](
			httpClient,
			baseURL+JobExecutionServiceAcquireExecutionProcedure,
			connect.WithSchema(jobExecutionServiceMethods.ByName("AcquireExecution")),
			connect.WithClientOptions(opts...),
		),
		streamEvents: connect.NewClient[StreamEventsRequest, StreamEventsResponse](
			httpClient,
			baseURL+JobExecutionServiceStreamEventsProcedure,
			connect.WithSchema(jobExecutionServiceMethods.ByName("StreamEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// jobExecutionServiceClient implements JobExecutionServiceClient.
type jobExecutionServiceClient struct {
	acquireExecution *connect.Client[AcquireExecutionRequest, AcquireExecutionResponse]
	streamEvents     *connect.Client[StreamEventsRequest, StreamEventsResponse]
}

// AcquireExecution calls bountyhub.job.execution.v1.JobExecutionService.AcquireExecution.
func (c *jobExecutionServiceClient) AcquireExecution(ctx context.Context, req *connect.Request[AcquireExecutionRequest]) (*connect.Response[AcquireExecutionResponse], error) {
	return c.acquireExecution.CallUnary(ctx, req)
}

// StreamEvents calls bountyhub.job.execution.v1.JobExecutionService.StreamEvents.
func (c *jobExecutionServiceClient) StreamEvents(ctx context.Context) *connect.ClientStreamForClient[StreamEventsRequest, StreamEventsResponse] {
	return c.streamEvents.CallClientStream(ctx)
}

// JobExecutionServiceHandler is an implementation of the
// bountyhub.job.execution.v1.JobExecutionService service.
type JobExecutionServiceHandler interface {
	AcquireExecution(context.Context, *connect.Request[AcquireExecutionRequest]) (*connect.Response[AcquireExecutionResponse], error)
	StreamEvents(context.Context, *connect.ClientStream[StreamEventsRequest]) (*connect.Response[StreamEventsResponse], error)
}

// NewJobExecutionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewJobExecutionServiceHandler(svc JobExecutionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	jobExecutionServiceMethods := File_job_execution_v1_proto.Services().ByName("JobExecutionService").Methods()
	jobExecutionServiceAcquireExecutionHandler := connect.NewUnaryHandler(
		JobExecutionServiceAcquireExecutionProcedure,
		svc.AcquireExecution,
		connect.WithSchema(jobExecutionServiceMethods.ByName("AcquireExecution")),
		connect.WithHandlerOptions(opts...),
	)
	jobExecutionServiceStreamEventsHandler := connect.NewClientStreamHandler(
		JobExecutionServiceStreamEventsProcedure,
		svc.StreamEvents,
		connect.WithSchema(jobExecutionServiceMethods.ByName("StreamEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bountyhub.job.execution.v1.JobExecutionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case JobExecutionServiceAcquireExecutionProcedure:
			jobExecutionServiceAcquireExecutionHandler.ServeHTTP(w, r)
		case JobExecutionServiceStreamEventsProcedure:
			jobExecutionServiceStreamEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedJobExecutionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedJobExecutionServiceHandler struct{}

func (UnimplementedJobExecutionServiceHandler) AcquireExecution(context.Context, *connect.Request[AcquireExecutionRequest]) (*connect.Response[AcquireExecutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bountyhub.job.execution.v1.JobExecutionService.AcquireExecution is not implemented"))
}

func (UnimplementedJobExecutionServiceHandler) StreamEvents(context.Context, *connect.ClientStream[StreamEventsRequest]) (*connect.Response[StreamEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bountyhub.job.execution.v1.JobExecutionService.StreamEvents is not implemented"))
}
