name: "Publish image"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version of the runner
        required: true

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: "Prepare environment"
        run: |
          echo "IMAGE_TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "IMAGE_NAME=bountyhuborg/runner" >> $GITHUB_ENV
          echo "BUILD_PLATFORMS=linux/amd64" >> $GITHUB_ENV
      - name: Validate input
        run: |
          if [[ "${IMAGE_TAG}" =~ ^[0-9]+.[0-9]+.[0-9]+$ ]]; then
            echo "Tag validation succeeded"
          else
            exit 1
          fi
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.inputs.version }}"
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker buildx build --platform="${BUILD_PLATFORMS}" \
            -f images/Dockerfile \
            -t "${IMAGE_NAME}:${IMAGE_TAG}" \
            . --push
        shell: bash
